name: guarch
description: Guarch Protocol - Censorship Circumvention App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_animate: ^4.3.0
  google_fonts: ^6.1.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  flutter_local_notifications: ^16.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#1E3543"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
