name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          channel: stable

      - name: Create Flutter Project
        run: |
          flutter create --project-name guarch --org com.guarch temp_project
          cp -r temp_project/android app/android
          cp -r temp_project/ios app/ios
          cp -r temp_project/web app/web
          rm -rf temp_project

      - name: Dependencies
        working-directory: app
        run: flutter pub get

      - name: Generate App Icon
        working-directory: app
        run: dart run flutter_launcher_icons

      - name: Build APK
        working-directory: app
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: guarch-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
